--SQL file
INSERT INTO MEDICO_ENTITY (ID, APELLIDO, ESPECIALIDAD, NOMBRE, REGISTRO_MEDICO) VALUES (1, 'Juan Jose', 'Rodriguez Ortiz', 'FC3578K', 'Anestesiología');
INSERT INTO MEDICO_ENTITY (ID, APELLIDO, ESPECIALIDAD, NOMBRE, REGISTRO_MEDICO) VALUES (2, 'Maria Paula', 'Sarmiento Mancipe', 'DE7825', 'Medicina Interna');